xml source
sourcevalidsa051xml
	"Source file: xmltest/valid/sa/051.xml"

	^ '<!DOCTYPE ', 16rE40 asCharacter asString, 16rE08 asCharacter asString, 16rE21 asCharacter asString, 16rE2A asCharacter asString, 16rE4C asCharacter asString, ' [
<!ELEMENT ', 16rE40 asCharacter asString, 16rE08 asCharacter asString, 16rE21 asCharacter asString, 16rE2A asCharacter asString, 16rE4C asCharacter asString, '  (#PCDATA)>
]>
<', 16rE40 asCharacter asString, 16rE08 asCharacter asString, 16rE21 asCharacter asString, 16rE2A asCharacter asString, 16rE4C asCharacter asString, '></', 16rE40 asCharacter asString, 16rE08 asCharacter asString, 16rE21 asCharacter asString, 16rE2A asCharacter asString, 16rE4C asCharacter asString, '>
'